# Generated by Django 5.2.3 on 2025-07-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file', models.FileField(upload_to='data_files/', verbose_name='Файл')),
                ('created_at', models.DateField(verbose_name='Дата создания')),
            ],
        ),
    ]
