# Generated by Django 5.2.3 on 2025-07-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.TextField()),
                ('file_date', models.DateField()),
            ],
            options={
                'db_table': 'files',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DataFile',
        ),
    ]
