# Generated by Django 5.2.4 on 2025-07-21 11:49

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_file_delete_datafile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('staid', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('staname', models.TextField(blank=True, null=True)),
                ('longstaname', models.TextField(blank=True, null=True)),
                ('network', models.TextField(blank=True, null=True)),
                ('agency', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('receiver', models.TextField(blank=True, null=True)),
                ('recvers', models.TextField(blank=True, null=True)),
                ('recnum', models.TextField(blank=True, null=True)),
                ('antenna', models.TextField(blank=True, null=True)),
                ('antnum', models.TextField(blank=True, null=True)),
                ('deltan', models.FloatField(blank=True, null=True)),
                ('deltae', models.FloatField(blank=True, null=True)),
                ('deltah', models.FloatField(blank=True, null=True)),
                ('startdate', models.TextField(blank=True, null=True)),
                ('enddate', models.TextField(blank=True, null=True)),
                ('sta_daterange', django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stations',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='file',
            table='stations_files',
        ),
    ]
